// Engine command contract.
//
// All UI parameter changes flow through this command shape on their way
// to the (future) DSP engine.  For now nothing downstream consumes
// commands — the provider in `useModuleParameterState.tsx` only keeps a
// rolling log for inspection.  M3-P-NEXT-5B will dispatch commands to
// the engine bridge.
//
// Why an explicit command type:
//   • Validation and clamping happen exactly once, when the command is
//     constructed.  Panels and the engine bridge agree on the same
//     (in-range, step-aligned) value.
//   • The log is auditable — every UI value change is replayable, which
//     helps debugging, A/B comparison, and future automation.
//   • Source tagging (`'user'` vs `'preset'` vs `'reference'`) keeps the
//     adapter loop "preset → state → preset" idempotent later on.

import type {
  AllModulesDefinitions,
  ModuleId,
  ParameterDef,
  ParameterValue,
} from './parameter-state.js';
import { findParameterDef } from './parameter-state.js';

// ── Sources / kinds ──────────────────────────────────────────────────────

export type CommandSource =
  /** Generated by direct UI interaction (slider drag, knob turn, toggle click). */
  | 'user'
  /** Generated when loading a preset (LOAD_PRESET ripple). */
  | 'preset'
  /** Generated by reference-profile application (APPLY_REFERENCE_PROFILE). */
  | 'reference'
  /** Generated by RESET_MODULE / RESET_ALL. */
  | 'reset'
  /** Generated programmatically by tests / storybook. */
  | 'system';

export type CommandKind =
  | 'SET_MODULE_PARAM'
  | 'SET_MODULE_BYPASS'
  | 'RESET_MODULE'
  | 'LOAD_PRESET'
  | 'APPLY_REFERENCE_PROFILE'
  | 'EXPORT_DESCRIPTOR_UPDATE';

// ── Validation ───────────────────────────────────────────────────────────

export type ValidationResult =
  | { status: 'ok';       value: ParameterValue }
  | { status: 'clamped';  from: ParameterValue; to: ParameterValue; reason: string }
  | { status: 'rejected'; original: ParameterValue; reason: string };

/**
 * Validate + clamp + quantise a candidate value against a parameter def.
 *
 * Returns an `ok` / `clamped` / `rejected` triple.  `clamped` carries
 * the original + the corrected value so the UI can show "you tried -50
 * dB; we clamped it to -30 dB."
 */
export function validateParameterValue(
  def: ParameterDef,
  candidate: unknown,
): ValidationResult {
  switch (def.kind) {
    case 'number': {
      if (typeof candidate !== 'number' || !Number.isFinite(candidate)) {
        return {
          status: 'rejected',
          original: candidate as ParameterValue,
          reason:   'not-finite-number',
        };
      }
      // Step quantisation (snap to grid before clamping so the clamp
      // result is always a valid step value).
      const quant = def.step > 0
        ? Math.round(candidate / def.step) * def.step
        : candidate;
      const clamped = Math.max(def.min, Math.min(def.max, quant));
      // Compare against original `candidate`, not `quant` — the user
      // cares that we deviated from the value they sent, not that we
      // rounded internally.
      if (clamped !== candidate) {
        const reason = clamped !== quant ? 'out-of-range' : 'step-quantised';
        return { status: 'clamped', from: candidate, to: clamped, reason };
      }
      return { status: 'ok', value: clamped };
    }
    case 'boolean': {
      if (typeof candidate !== 'boolean') {
        return {
          status: 'rejected',
          original: candidate as ParameterValue,
          reason:   'not-boolean',
        };
      }
      return { status: 'ok', value: candidate };
    }
    case 'enum': {
      if (typeof candidate !== 'string') {
        return {
          status: 'rejected',
          original: candidate as ParameterValue,
          reason:   'not-string',
        };
      }
      if (!def.values.includes(candidate)) {
        return {
          status: 'rejected',
          original: candidate,
          reason:   `not-in-enum [${def.values.join(', ')}]`,
        };
      }
      return { status: 'ok', value: candidate };
    }
  }
}

// ── Command shapes ───────────────────────────────────────────────────────

export interface BaseCommand {
  kind: CommandKind;
  /** `performance.now()` at construction time. */
  timestamp: number;
  source: CommandSource;
}

export interface SetModuleParamCommand extends BaseCommand {
  kind: 'SET_MODULE_PARAM';
  moduleId: ModuleId;
  parameterId: string;
  value: ParameterValue;
  validation: ValidationResult;
}

export interface SetModuleBypassCommand extends BaseCommand {
  kind: 'SET_MODULE_BYPASS';
  moduleId: ModuleId;
  bypass: boolean;
}

export interface ResetModuleCommand extends BaseCommand {
  kind: 'RESET_MODULE';
  moduleId: ModuleId;
}

export interface LoadPresetCommand extends BaseCommand {
  kind: 'LOAD_PRESET';
  presetId: string;
  presetName?: string;
}

export interface ApplyReferenceProfileCommand extends BaseCommand {
  kind: 'APPLY_REFERENCE_PROFILE';
  profileId: string;
  profileName?: string;
}

export interface ExportDescriptorUpdateCommand extends BaseCommand {
  kind: 'EXPORT_DESCRIPTOR_UPDATE';
  /** Full export descriptor — format / sample rate / bit depth / dither. */
  descriptor: {
    format:     string;
    sampleRate: string;
    bitDepth:   string;
    dither:     string;
  };
}

export type EngineCommand =
  | SetModuleParamCommand
  | SetModuleBypassCommand
  | ResetModuleCommand
  | LoadPresetCommand
  | ApplyReferenceProfileCommand
  | ExportDescriptorUpdateCommand;

// ── Constructors ─────────────────────────────────────────────────────────

const now = (): number => (typeof performance !== 'undefined' ? performance.now() : Date.now());

export function makeSetParamCommand(args: {
  defs:        AllModulesDefinitions;
  moduleId:    ModuleId;
  parameterId: string;
  candidate:   unknown;
  source?:     CommandSource;
}): SetModuleParamCommand {
  const def = findParameterDef(args.defs, args.moduleId, args.parameterId);
  const validation = validateParameterValue(def, args.candidate);
  // The resulting `value` field always reflects what actually goes into
  // state — clamped if clamped, original if ok, unchanged-from-default if
  // rejected (caller decides whether to apply rejected commands).
  const value: ParameterValue =
    validation.status === 'ok' ? validation.value :
    validation.status === 'clamped' ? validation.to :
    def.default;
  return {
    kind: 'SET_MODULE_PARAM',
    timestamp: now(),
    source: args.source ?? 'user',
    moduleId: args.moduleId,
    parameterId: args.parameterId,
    value,
    validation,
  };
}

export function makeSetBypassCommand(args: {
  moduleId: ModuleId;
  bypass:   boolean;
  source?:  CommandSource;
}): SetModuleBypassCommand {
  return {
    kind: 'SET_MODULE_BYPASS',
    timestamp: now(),
    source: args.source ?? 'user',
    moduleId: args.moduleId,
    bypass: args.bypass,
  };
}

export function makeResetModuleCommand(args: {
  moduleId: ModuleId;
  source?:  CommandSource;
}): ResetModuleCommand {
  return {
    kind: 'RESET_MODULE',
    timestamp: now(),
    source: args.source ?? 'reset',
    moduleId: args.moduleId,
  };
}

export function makeLoadPresetCommand(args: {
  presetId:   string;
  presetName?: string;
  source?:    CommandSource;
}): LoadPresetCommand {
  const cmd: LoadPresetCommand = {
    kind: 'LOAD_PRESET',
    timestamp: now(),
    source: args.source ?? 'preset',
    presetId: args.presetId,
  };
  if (args.presetName !== undefined) cmd.presetName = args.presetName;
  return cmd;
}

export function makeApplyReferenceCommand(args: {
  profileId:   string;
  profileName?: string;
  source?:     CommandSource;
}): ApplyReferenceProfileCommand {
  const cmd: ApplyReferenceProfileCommand = {
    kind: 'APPLY_REFERENCE_PROFILE',
    timestamp: now(),
    source: args.source ?? 'reference',
    profileId: args.profileId,
  };
  if (args.profileName !== undefined) cmd.profileName = args.profileName;
  return cmd;
}

export function makeExportDescriptorCommand(args: {
  descriptor: ExportDescriptorUpdateCommand['descriptor'];
  source?:    CommandSource;
}): ExportDescriptorUpdateCommand {
  return {
    kind: 'EXPORT_DESCRIPTOR_UPDATE',
    timestamp: now(),
    source: args.source ?? 'user',
    descriptor: args.descriptor,
  };
}

// ── Logging helpers (for the dev / Storybook command log view) ──────────

/**
 * Compact single-line representation of a command for the log view.
 *
 * Example: "user · SET_MODULE_PARAM eq.lowShelfDb = 3.5 dB (clamped from 8 dB)"
 */
export function describeCommand(cmd: EngineCommand): string {
  const ts = cmd.timestamp.toFixed(0);
  switch (cmd.kind) {
    case 'SET_MODULE_PARAM': {
      const v = JSON.stringify(cmd.value);
      const tag =
        cmd.validation.status === 'ok' ? '' :
        cmd.validation.status === 'clamped' ?
          ` (clamped from ${JSON.stringify(cmd.validation.from)})` :
          ` (rejected: ${cmd.validation.reason})`;
      return `[${ts}] ${cmd.source} · SET ${cmd.moduleId}.${cmd.parameterId} = ${v}${tag}`;
    }
    case 'SET_MODULE_BYPASS':
      return `[${ts}] ${cmd.source} · BYPASS ${cmd.moduleId} = ${cmd.bypass}`;
    case 'RESET_MODULE':
      return `[${ts}] ${cmd.source} · RESET ${cmd.moduleId}`;
    case 'LOAD_PRESET':
      return `[${ts}] ${cmd.source} · LOAD_PRESET ${cmd.presetId}`;
    case 'APPLY_REFERENCE_PROFILE':
      return `[${ts}] ${cmd.source} · APPLY_REFERENCE_PROFILE ${cmd.profileId}`;
    case 'EXPORT_DESCRIPTOR_UPDATE':
      return `[${ts}] ${cmd.source} · EXPORT_DESCRIPTOR ${JSON.stringify(cmd.descriptor)}`;
  }
}
